patterns = [
    # CONTESTANT patterns
    {"label": "CONTESTANT", "pattern": [{"LOWER": "shkodra"}, {"LOWER": "elektronike"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "parg"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "go-jo"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "jj"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "mamagama"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "red"}, {"LOWER": "sebastian"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "marko"}, {"LOWER": "bošnjak"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "theo"}, {"LOWER": "evan"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "adonxs"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "sissal"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "tommy"}, {"LOWER": "cash"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "erika"}, {"LOWER": "vikman"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "louane"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "mariam"}, {"LOWER": "shengelia"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "abor"}, {"LOWER": "&"}, {"LOWER": "tynna"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "klavdia"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "væb"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "emmy"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "yuval"}, {"LOWER": "raphael"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "lucio"}, {"LOWER": "corsi"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "tautumeitas"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "katarsis"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "laura"}, {"LOWER": "thorn"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "miriana"}, {"LOWER": "conte"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "nina"}, {"LOWER": "žižić"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "claude"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "kyle"}, {"LOWER": "alessandro"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "justyna"}, {"LOWER": "steczkowska"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "napa"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "gabry"}, {"LOWER": "ponte"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "princ"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "klemen"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "melody"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "kaj"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "zoë"}, {"LOWER": "më"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "ziferblat"}]},
    {"label": "CONTESTANT", "pattern": [{"LOWER": "remember"}, {"LOWER": "monday"}]},

    # SONG title patterns
    {"label": "SONG", "pattern": [{"LOWER": "zjerm"}]},
    {"label": "SONG", "pattern": [{"LOWER": "survivor"}]},
    {"label": "SONG", "pattern": [{"LOWER": "milkshake"}, {"LOWER": "man"}]},
    {"label": "SONG", "pattern": [{"LOWER": "wasted"}, {"LOWER": "love"}]},
    {"label": "SONG", "pattern": [{"LOWER": "run"}, {"LOWER": "with"}, {"LOWER": "u"}]},
    {"label": "SONG", "pattern": [{"LOWER": "strobe"}, {"LOWER": "lights"}]},
    {"label": "SONG", "pattern": [{"LOWER": "poison"}, {"LOWER": "cake"}]},
    {"label": "SONG", "pattern": [{"LOWER": "shh"}]},
    {"label": "SONG", "pattern": [{"LOWER": "kiss"}, {"LOWER": "kiss"}, {"LOWER": "goodbye"}]},
    {"label": "SONG", "pattern": [{"LOWER": "hallucination"}]},
    {"label": "SONG", "pattern": [{"LOWER": "espresso"}, {"LOWER": "macchiato"}]},
    {"label": "SONG", "pattern": [{"LOWER": "ich"}, {"LOWER": "komme"}]},
    {"label": "SONG", "pattern": [{"LOWER": "maman"}]},
    {"label": "SONG", "pattern": [{"LOWER": "freedom"}]},
    {"label": "SONG", "pattern": [{"LOWER": "baller"}]},
    {"label": "SONG", "pattern": [{"LOWER": "asteromáta"}]},
    {"label": "SONG", "pattern": [{"LOWER": "róa"}]},
    {"label": "SONG", "pattern": [{"LOWER": "laika"}, {"LOWER": "party"}]},
    {"label": "SONG", "pattern": [{"LOWER": "new"}, {"LOWER": "day"}, {"LOWER": "will"}, {"LOWER": "rise"}]},
    {"label": "SONG", "pattern": [{"LOWER": "volevo"}, {"LOWER": "essere"}, {"LOWER": "un"}, {"LOWER": "duro"}]},
    {"label": "SONG", "pattern": [{"LOWER": "bur"}, {"LOWER": "man"}, {"LOWER": "laimi"}]},
    {"label": "SONG", "pattern": [{"LOWER": "tavo"}, {"LOWER": "akys"}]},
    {"label": "SONG", "pattern": [{"LOWER": "la"}, {"LOWER": "poupée"}, {"LOWER": "monte"}, {"LOWER": "le"}, {"LOWER": "son"}]},
    {"label": "SONG", "pattern": [{"LOWER": "serving"}]},
    {"label": "SONG", "pattern": [{"LOWER": "dobrodošli"}]},
    {"label": "SONG", "pattern": [{"LOWER": "c’est"}, {"LOWER": "la"}, {"LOWER": "vie"}]},
    {"label": "SONG", "pattern": [{"LOWER": "lighter"}]},
    {"label": "SONG", "pattern": [{"LOWER": "gaja"}]},
    {"label": "SONG", "pattern": [{"LOWER": "deslocado"}]},
    {"label": "SONG", "pattern": [{"LOWER": "tutta"}, {"LOWER": "l’italia"}]},  
    {"label": "SONG", "pattern": [{"LOWER": "mila"}]},
    {"label": "SONG", "pattern": [{"LOWER": "how"}, {"LOWER": "much"}, {"LOWER": "time"}, {"LOWER": "do"}, {"LOWER": "we"}, {"LOWER": "have"}, {"LOWER": "left"}]},
    {"label": "SONG", "pattern": [{"LOWER": "esa"}, {"LOWER": "diva"}]},
    {"label": "SONG", "pattern": [{"LOWER": "bara"}, {"LOWER": "bada"}, {"LOWER": "bastu"}]},
    {"label": "SONG", "pattern": [{"LOWER": "voyage"}]},
    {"label": "SONG", "pattern": [{"LOWER": "bird"}, {"LOWER": "of"}, {"LOWER": "pray"}]},
    {"label": "SONG", "pattern": [{"LOWER": "what"}, {"LOWER": "the"}, {"LOWER": "hell"}, {"LOWER": "just"}, {"LOWER": "happened"}]}
]
